[package]
name = "frida"
version = "0.3.0"
authors = ["Keegan Saunders <keegan@undefinedbehaviour.org>"]
edition = "2021"
license = "wxWindows"
repository = "https://github.com/frida/frida-rust"
description = "Rust bindings for Frida"

[features]
auto-download = ["frida-sys/auto-download"]

[dependencies]
frida-sys = { path = "../frida-sys", version = "0.3.0" }
thiserror = "1"

[dev-dependencies]
lazy_static = "1"

[badges]
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = []
rustdoc-args = ["--cfg", "doc_cfg"]
